"""
Prompt templates for the Company Researcher workflow.

This module contains all prompts used by the LLM at different stages
of the research workflow.
"""


# ============================================================================
# Query Generation
# ============================================================================

GENERATE_QUERIES_PROMPT = """You are a research assistant tasked with gathering comprehensive information about a company.

Company: {company_name}

Generate {num_queries} specific, targeted search queries that will help research this company thoroughly.

Your queries should cover:
1. Company overview and background
2. Financial performance and metrics
3. Products and services
4. Market position and competitors
5. Recent news and developments

Requirements:
- Each query should be specific and focused
- Queries should complement each other (no redundancy)
- Use exact company name in queries
- Keep queries concise (3-10 words each)

Output format:
Return ONLY a JSON array of query strings, nothing else.

Example output:
["Tesla company overview history", "Tesla revenue 2024 financial performance", "Tesla Model Y Model 3 sales", "Tesla vs General Motors market share", "Tesla Cybertruck latest news"]

Now generate {num_queries} queries for {company_name}:"""


# ============================================================================
# Analysis and Summarization
# ============================================================================

ANALYZE_RESULTS_PROMPT = """You are a research analyst reviewing web search results about a company.

Company: {company_name}

Search Results:
{search_results}

Task: Analyze these search results and extract key information.

Please create concise notes covering:
1. Key facts about the company (founding, leadership, size)
2. Financial metrics (revenue, funding, profitability)
3. Main products or services
4. Market position and competitors
5. Recent developments or news

Requirements:
- Be factual and objective
- Only include information found in the search results
- If a piece of information is unclear or missing, note that
- Keep notes concise but comprehensive

Format your notes as clear bullet points."""


# ============================================================================
# Structured Data Extraction
# ============================================================================

EXTRACT_DATA_PROMPT = """You are a data extraction specialist analyzing research notes about a company.

Company: {company_name}

Research Notes:
{notes}

Search Sources:
{sources}

Task: Extract structured information into the following categories.

Please provide:

## Company Overview
A 2-3 sentence summary of the company, its purpose, and what it does.

## Key Metrics
Extract any available metrics as key-value pairs:
- Revenue: [amount and year]
- Employees: [number]
- Founded: [year]
- Valuation: [amount if private] or Market Cap: [amount if public]
- Funding: [total raised if applicable]
- Any other relevant metrics

## Main Products/Services
List the company's primary products or services (bullet points)

## Competitors
List 3-5 main competitors if mentioned

## Key Insights
List 2-3 most important or interesting facts about the company

Requirements:
- Only include information explicitly stated in the notes
- If a section has no information, write "Not available in research"
- Be precise with numbers and dates
- Format as clean markdown

Extract the structured data now:"""


# ============================================================================
# Report Generation
# ============================================================================

GENERATE_REPORT_TEMPLATE = """# {company_name} - Research Report

*Generated on {date}*

---

## Company Overview

{company_overview}

---

## Key Metrics

{key_metrics}

---

## Main Products & Services

{products_services}

---

## Competitive Landscape

{competitors}

---

## Key Insights

{key_insights}

---

## Sources

{sources}

---

*This report was automatically generated by the Company Researcher System*
*Research completed in {duration:.1f} seconds | Cost: ${cost:.4f} | Sources: {source_count}*
"""


# ============================================================================
# Quality Check (Phase 2)
# ============================================================================

QUALITY_CHECK_PROMPT = """You are a quality assurance specialist reviewing company research.

Company: {company_name}

Extracted Information:
{extracted_data}

Available Sources:
{sources}

Task: Evaluate the quality and completeness of this research.

Please assess:

1. **Completeness** (0-40 points):
   - Does it have company overview? (10 points)
   - Does it have key financial metrics? (10 points)
   - Does it have products/services? (10 points)
   - Does it have competitive analysis? (10 points)

2. **Accuracy** (0-30 points):
   - Are facts supported by sources? (15 points)
   - Are numbers/dates specific and verifiable? (15 points)

3. **Depth** (0-30 points):
   - Is the analysis insightful? (15 points)
   - Does it go beyond surface-level information? (15 points)

Provide your assessment in this exact JSON format:
{{
  "quality_score": <number 0-100>,
  "missing_information": [
    "Specific information that's missing or incomplete",
    "Another missing piece",
    ...
  ],
  "strengths": [
    "What's good about this research",
    ...
  ],
  "recommended_queries": [
    "Specific search query to fill gap 1",
    "Specific search query to fill gap 2",
    ...
  ]
}}

Be strict: Only score 85+ if the research is truly comprehensive and well-sourced."""


# ============================================================================
# Helper Functions
# ============================================================================

def format_search_results_for_analysis(results: list) -> str:
    """
    Format search results for the analysis prompt.

    Args:
        results: List of search result dictionaries

    Returns:
        Formatted string of search results
    """
    formatted = []
    for i, result in enumerate(results, 1):
        formatted.append(f"""
Result {i}:
Title: {result.get('title', 'N/A')}
URL: {result.get('url', 'N/A')}
Content: {result.get('content', 'N/A')}
Score: {result.get('score', 0):.0%}
---
""")
    return "\n".join(formatted)


def format_sources_for_extraction(sources: list) -> str:
    """
    Format sources for the extraction prompt.

    Args:
        sources: List of source dictionaries

    Returns:
        Formatted string of sources
    """
    formatted = []
    for i, source in enumerate(sources, 1):
        formatted.append(
            f"{i}. [{source.get('title', 'N/A')}]({source.get('url', 'N/A')}) "
            f"(Relevance: {source.get('score', 0):.0%})"
        )
    return "\n".join(formatted)


def format_sources_for_report(sources: list) -> str:
    """
    Format sources for the final report.

    Args:
        sources: List of source dictionaries

    Returns:
        Formatted markdown list of sources
    """
    formatted = []
    for i, source in enumerate(sources, 1):
        formatted.append(
            f"{i}. [{source.get('title', 'N/A')}]({source.get('url', 'N/A')})"
        )
    return "\n".join(formatted)
